pipeline {

 agent any
 
 stages {
  
  stage ("Git checkout") {
   steps {   
    git 'https://github.com/manu1rock/newocean.git'  
    }
  }
  
  stage ("Build") {
   steps {   
    script {
     bat 'mvn compile'
    }  
    }
  }
  
  
 
 }

}
