pipeline {

 agent any
 
 stages {
  
  stage ("Git checkout") {
   steps {   
    git 'https://github.com/manu1rock/newocean.git'  
    }
  }
  
  stage ("Build") {
   steps {   
    dir('newocean') {
     script {
      bat 'mvn compile'
      }  
    }    
    }
  }
  
  stage ("Test") {
   steps { 
    dir('newocean') {
     script {
      bat 'mvn test'
      }  
     }   
    }
  }
  
  
 
 }

}
